ICD10_CODES = {
    'I269': 'Pulmonary embolism without acute cor pulmonale',
    'I519': 'Other heart diseases in diseases classified elsewhere',
    'I351': 'Nonrheumatic aortic valve disorders',
    'I848': 'Other specified disorders of arteries and arterioles',
    'I481': 'Atrial fibrillation and flutter',
    'I846': 'Spontaneous dissection of other specified arteries',
    'I495': 'Sudden cardiac death, so described',
    'I441': 'Aneurysm of artery of lower extremity',
    'I083': 'Hypertensive heart and chronic kidney disease with heart failure and stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease',
    'I639': 'Cerebral infarction, unspecified',
    'I802': 'Acute embolism and thrombosis of superior mesenteric artery',
    'I730': 'Aneurysm of aorta',
    'I249': 'Other forms of chronic ischemic heart disease',
    'I500': 'Congestive heart failure',
    'I743': 'Embolism and thrombosis of renal artery',
    'I831': 'Varicose veins of lower extremities',
    'I081': 'Hypertensive heart and chronic kidney disease with heart failure and stage 5 chronic kidney disease, or end stage renal disease',
    'I714': 'Arteritis, unspecified',
    'I460': 'Acute heart failure',
    'I771': 'Other secondary and unspecified cardiomyopathies',
    'I517': 'Cardiomegaly',
    'I251': 'Atherosclerotic heart disease of native coronary artery',
    'I859': 'Other and unspecified atherosclerosis',
    'I493': 'Chronic obstructive pulmonary disease',
    'I252': 'Old myocardial infarction',
    'I071': 'Hypertensive heart disease with heart failure',
    'I211': 'Benign neoplasm of colon',
    'I442': 'Aneurysm of artery of upper extremity',
    'I841': 'Abdominal aortic aneurysm, without rupture',
    'I313': 'Dermatitis',
    'I842': 'Abdominal aortic aneurysm, ruptured',
    'I518': 'Other and unspecified heart diseases originating in the perinatal period',
    'I451': 'Esophageal varices with bleeding',
    'I849': 'Other specified disorders of circulatory system',
    'I499': 'Unspecified disorder of circulatory system',
    'I64': 'Stroke, not specified as hemorrhage or infarction',
    'I259': 'Chronic ischemic heart disease, unspecified',
    'I350': 'Atherosclerosis of aorta',
    'I272': 'Other disorders of pulmonary circulation',
    'I471': 'Atherosclerosis of renal artery',
    'I951': 'Intraoperative hemorrhage and hematoma of a circulatory system organ or structure complicating a procedure',
    'I480': 'Paroxysmal atrial fibrillation',
    'I200': 'Angina pectoris',
    'I694': 'Granulomatosis with polyangiitis (Wegener)',
    'I447': 'Aneurysm of other specified artery',
    'I208': 'Angina pectoris, unspecified',
    'I120': 'Hypertensive heart disease with renal disease',
    'I420': 'Acute myocarditis',
    'I501': 'Left ventricular failure',
    'I959': 'Hypothyroidism, unspecified',
    'I652': 'Other transient cerebral ischemic attacks and related syndromes',
    'I48': 'Atrial fibrillation and flutter',
    'I219': 'Subacute myocardial infarction, unspecified',
    'I739': 'Peripheral vascular disease, unspecified',
    'I509': 'Heart failure, unspecified',
    'I489': 'Atrial fibrillation and flutter',
    'I10': 'Essential (primary) hypertension',
    'I209': 'Angina pectoris, unspecified',
    'I258': 'Chronic ischemic heart disease, unspecified',
    'I679': 'Cerebrovascular disease, unspecified',
    'I678': 'Cerebrovascular disease, unspecified',
    'I341': 'Mitral valve insufficiency',
    'I635': 'Cerebral infarction due to thrombosis of cerebral arteries',
    'I429': 'Cardiomyopathy, unspecified',
    'I7020': 'Acute and subacute ICD-10 code range I7020',
    'I214': 'Other acute ischemic heart diseases',
    'I080': 'Hypertensive heart and chronic kidney disease with heart failure and stage 5 chronic kidney disease, or end stage renal disease',
    'I890': 'Other specified noninfective gastroenteritis and colitis',
    'I472': 'Atherosclerosis of autologous vein coronary artery bypass graft',
    'I440': 'Aneurysm of thoracic aorta',
    'I210': 'Atherosclerotic heart disease',
    'I839': 'Other specified diseases of arteries and arterioles',
    'I340': 'Mitral valve stenosis',
}
